routes/web.php
<?php

use App\Http\Controllers\AttemptsController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Services\CurrencyLayer;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', HomeController::class)->name('home');

Route::get('/maximos-intentos', AttemptsController::class)->name('attempts');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
});

app/Models/Currency.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

final class Currency extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'code',
        'status',
    ];
}

app/Models/CurrencyRequest.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

final class CurrencyRequest extends Model
{
    protected $fillable = [
        'user_id',
        'from',
        'to',
        'amount',
        'result',
        'ip',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

final class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array<int, string>
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function currencyRequests(): HasMany
    {
        return $this->hasMany(CurrencyRequest::class);
    }
}

app/Http/Controllers/AttemptsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\View\View;

final class AttemptsController extends Controller
{
    public function __invoke(): View
    {
        return view('attempts');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Auth;

final class DashboardController extends Controller
{
    public function __invoke(): View
    {
        return view('dashboard', [
            'transactions' => Auth::user()->currencyRequests,
        ]);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\View\View;

final class HomeController extends Controller
{
    public function __invoke(): View
    {
        return view('home');
    }
}

app/Livewire/ConverterCard.php
<?php

namespace App\Livewire;

use App\Contracts\CurrencyInterface;
use App\Contracts\SessionInterface;
use App\DTO\CurrencyRequestDto;
use App\Models\Currency;
use App\Repositories\Contracts\CurrencyRequestsRepositoryInterface;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;

final class ConverterCard extends Component
{
    private const INITIAL_CURRENCY_CURRENT = 'USD-United States Dollar';
    private const INITIAL_CURRENCY_TARGET = 'EUR-Euro';
    private const INITIAL_AMOUNT = 1;
    private const MAX_ATTEMPTS = 5;

    private CurrencyInterface $currencyService;
    private SessionInterface $session;
    private CurrencyRequestsRepositoryInterface $currencyRequestRepository;

    public string $from = self::INITIAL_CURRENCY_CURRENT;
    public string $to = self::INITIAL_CURRENCY_TARGET;
    public float $amount = self::INITIAL_AMOUNT;
    public int $attempts = self::MAX_ATTEMPTS;
    public float $result = 0.0;
    public array $requests = [];

    public function rules(): array
    {
        return [
            'from' => 'required',
            'to' => 'required',
            'amount' => 'required|numeric|min:0.01',
        ];
    }

    public function mount(): void
    {
        $this->validateAttempts();
        $this->convert();
    }

    public function boot(
        SessionInterface $session,
        CurrencyInterface $currencyService,
        CurrencyRequestsRepositoryInterface $currencyRequestRepository
    ): void
    {
        $this->session = $session;
        $this->currencyService = $currencyService;
        $this->currencyRequestRepository = $currencyRequestRepository;
    }

    public function render(): View
    {
        return view('livewire.converter-card', [
            'currencies' => Currency::all(),
        ]);
    }

    public function reverse(): void
    {
        $aux = $this->from;
        $this->from = $this->to;
        $this->to = $aux;
        $this->convert();
        $this->validateAttempts();
    }

    public function updated($value): void
    {
        $this->convert();
        $this->validateAttempts();
    }

    public function convert(): void
    {
        $this->validate();

        $from_code = explode('-', $this->from)[0];
        $to_code = explode('-', $this->to)[0];

        try {
            $this->result = $this->currencyService->convert(
                $from_code,
                $to_code,
                $this->amount
            );

            $currency_request = CurrencyRequestDto::create(
                userId: Auth::id(),
                from: $from_code,
                to: $to_code,
                amount: $this->amount,
                result: $this->result,
                ip: request()->ip()
            );
            $this->currencyRequestRepository->save($currency_request);

        } catch ( \Exception $e) {
        }

    }

    private function validateAttempts(): void
    {
        if(!is_null(Auth::user())) {
            return;
        }

        if (!$this->session->exists('attempts')) {
            $this->session->set('attempts', $this->attempts);
            return;
        }

        if ($this->session->get('attempts') == 0) {
            redirect()->route('attempts');
        }

        $this->attempts -= 1;
        $this->session->set('attempts', $this->attempts);
        if ($this->attempts === 0) {
            redirect()->route('attempts');
        }
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/attempts.blade.php
<x-guest-layout>
    <div class="py-12 bg-gray-100 min-h-screen">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="col-span-4">
                <!-- main card -->
                <div class="flex items-center justify-center bg-red-200">
                    <div class="w-full rounded-lg bg-white p-3 drop-shadow-xl divide-y divide-gray-200" >
                        <div aria-label="header" class="flex space-x-4 items-center p-4 font-bold text-blue-950 justify-between">
                            <span> Exchange For Software Engineers </span>
                            @if(Auth::user())
                                <span class="text-red-600">Haz consumido los cinco [5] usos*</span>
                            @endif
                        </div>
                        <div class="pt-10 px-6">
                            <!-- Results -->
                            <div>
                                <div class="text-lg text-semibold text-gray-700">
                                    Nos entristece informarte que haz consumido los cinco [5] usos gratuitos que tenías disponibles.
                                </div>
                                <div class="text-3xl text-bold">
                                    Te invitamos a registrarte en nuestra plataforma y disfrutar de todos los beneficios que tenemos para ti.
                                </div>
                                <div class="text-lg text-light text-gray-700">
                                    Hazlo! es gratis.
                                </div>
                                <div class="my-6">
                                    <a class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" href="{{route('register')}}">Registrarme</a>
                                </div>
                            </div>
                            <!-- Bottom info -->
                            <div class="text-end mb-10">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/dashboard.blade.php
<x-guest-layout>
    <div class="py-12 bg-gray-100 min-h-screen">
        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <section class="py-1 bg-blueGray-50">
                    <div class="w-full xl:w-8/12 mb-12 xl:mb-0 px-4 mx-auto mt-24">
                        <div class="relative flex flex-col min-w-0 break-words bg-white w-full mb-6 shadow-lg rounded-2xl">
                            <div class="rounded-t mb-0 px-4 py-3 border-0">
                                <div class="flex flex-wrap items-center">
                                    <div class="relative w-full px-4 max-w-full flex-grow flex-1">
                                        <h3 class="font-semibold text-base text-blueGray-700">Consultas al exchange</h3>
                                    </div>
                                </div>
                            </div>

                            <div class="block w-full overflow-x-auto">
                                <table class="items-center bg-transparent w-full border-collapse ">
                                    <thead>
                                    <tr>
                                        <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-center">
                                            Fecha
                                        </th>
                                        <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-center">
                                            Desde
                                        </th>
                                        <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-center">
                                            Hacia
                                        </th>
                                        <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-center">
                                            Cantidad
                                        </th>
                                        <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-center">
                                            Resultado
                                        </th>
                                        <th class="px-6 bg-blueGray-50 text-blueGray-500 align-middle border border-solid border-blueGray-100 py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-center">
                                            Ip
                                        </th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    @foreach($transactions as $transaction)
                                        <tr>
                                            <th class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-center text-blueGray-700 ">
                                                {{$transaction->created_at->format('d-m-Y H:i:s')}}
                                            </th>
                                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-center ">
                                                {{$transaction->from}}
                                            </td>
                                            <td class="border-t-0 px-6 align-center border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-center">
                                                {{$transaction->to}}
                                            </td>
                                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-center">
                                                <!--i class="fas fa-arrow-up text-emerald-500 mr-4"></i-->
                                                {{$transaction->amount}}
                                            </td>
                                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-center text-green-600">
                                                {{$transaction->result}}
                                            </td>
                                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-center">
                                                {{$transaction->ip}}
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>

                                </table>
                            </div>
                        </div>
                    </div>
                    <footer class="relative pt-8 pb-6 mt-16">
                    </footer>
                </section>
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/home.blade.php
<x-guest-layout>
    <div class="py-12 bg-gray-100 min-h-screen">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="col-span-4">
                <!-- main card -->
                <div class="flex items-center justify-center">
                    <div class="w-full rounded-lg bg-white p-3 drop-shadow-xl divide-y divide-gray-200" >
                        <livewire:converter-card />
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])

        <!-- Styles -->
        @livewireStyles
    </head>
    <body class="font-sans antialiased">
        <x-banner />

        <div class="min-h-screen bg-gray-100">
            @livewire('navigation-menu')

            <!-- Page Heading -->
            @if (isset($header))
                <header class="bg-white shadow">
                    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                        {{ $header }}
                    </div>
                </header>
            @endif

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>

        @stack('modals')

        @livewireScripts
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])

        <!-- Styles -->
        @livewireStyles
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            @livewire('navigation-menu')

            {{ $slot }}
        </div>

        @livewireScripts
    </body>
</html>

resources/views/livewire/converter-card.blade.php
<div>
    <div aria-label="header" class="flex space-x-4 items-center p-4 font-bold text-blue-950 justify-between">
        <span>Exchange For Software Engineers </span>
        @if(Auth::user())
            <span class="text-green-600">Usos ilimitados</span>
        @else
            <span>{{$attempts}} usos restantes*</span>
        @endif
    </div>
    <div class="pt-10 px-6">
        <!-- component -->
        <div class="grid grid-cols-1 md:grid-cols-10 gap-4 mb-8">
            <div class="col-span-3 mb-6 md:mb-0">
                <label class="block tracking-wide text-grey-darker font-bold mb-2" for="grid-first-name">
                    Importe
                </label>
                <input
                    class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3"
                    id="grid-first-name"
                    type="number"
                    placeholder="1,00"
                    min="1"
                    step="0.01"
                    wire:model.lazy="amount"
                >
                <p class="text-xs text-red-600">&nbsp
                    @error('amount')Introduzca una cantidad válida.@enderror
                </p>
            </div>
            <div class="col-span-3 mb-6 md:mb-0">
                <label class="block tracking-wide text-grey-darker font-bold mb-2" for="grid-state">
                    De:
                </label>
                <div class="relative">
                    <select
                        class="block appearance-none w-full bg-grey-lighter border border-grey-lighter text-grey-darker py-3 px-4 pr-8 rounded"
                        id="grid-state"
                        wire:model.lazy="from"
                    >
                        @foreach($currencies as $currency)
                            <option value="{{$currency->code}}-{{$currency->title}}" wire:key="{{ $currency->code }}">{{$currency->code}} - {{$currency->title}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-span-1 mb-6 md:mb-0 place-self-center">
                <img
                    class="rounded-full border border-black h-10 p-2 cursor-pointer"
                    src="{{asset('images/reverse.svg')}}"
                    alt="inverter"
                    wire:click="reverse"
                >
            </div>
            <div class="col-span-3 mb-6 md:mb-0">
                <label class="block tracking-wide text-grey-darker font-bold mb-2" for="grid-state">
                    Hacia:
                </label>
                <div class="relative">
                    <select
                        class="block appearance-none w-full bg-grey-lighter border border-grey-lighter text-grey-darker py-3 px-4 pr-8 rounded"
                        id="grid-state"
                        wire:model.lazy="to"
                    >
                        @foreach($currencies as $currency)
                            <option value="{{$currency->code}}-{{$currency->title}}" wire:key="{{ $currency->code }}">{{$currency->code}} - {{$currency->title}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
        <!-- Results -->
        <div>
            <div class="text-lg text-semibold text-gray-700">
                {{$amount}} {{explode('-', $from)[1]}} =
            </div>
            <div class="text-3xl text-bold">
                {{$result}} {{explode('-', $to)[1]}}
            </div>
            <div class="text-lg text-light text-gray-700">
                {{$amount}} {{explode('-', $from)[1]}} = {{$result}} {{explode('-', $to)[1]}}
            </div>
        </div>
        <!-- Bottom info -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div class="px-4 py-2 bg-blue-50 rounded-lg my-6 text-sm">
                Usamos la tasa del mercado medio para nuestro conversor.
                Esto solo tiene fines informativos.
                No recibirás esta tasa cuando envíes dinero.
                <span class="text-blue-700 cursor-pointer">Consulta las tasas de envío.</span>
            </div>
        </div>
        <div class="text-end mb-10">
            <p class="text-gray-700 text-xs">
                Conversión de <span class="text-blue-700 cursor-pointer">{{explode('-', $from)[1]}}</span> a
                <span class="text-blue-700 cursor-pointer">{{explode('-', $to)[1]}}</span> — Última actualización: {{now()->format('d/m/Y')}}
            </p>
            @if(!Auth::user())
                <p class="text-sm">
                    Solo tienes cinco usos gratuitos de este conversor de divisas.
                    <a class="text-blue-700" href="{{route('register')}}">Registrate</a> y podras usarlo ilimitadamente.
                </p>
            @endif
        </div>
    </div>
</div>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>